#!/bin/sh
set -e

case $1 in
    configure)
        for i in /usr/share/rockchip-iqfiles-rk3399/*
        do
            ln -fs "$i" "/etc/iqfiles/$(basename "$i")"
        done
        ;;
esac
    


exit 0
